### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by mmarkus13** [CollectiveIndustries/Mangos_Installer#12]
OSError: [Errno 13] Permission denied: '/home/mangos/SOURCE/mangos3_ci_code/server/objdir'

**Comment by Morketh** [comment]
Can you provide details on how you got this error?
The steps in order to reproduce it would also be helpful.
Operating system version  and architecture would also be helpful in fixing this issue.
Also were you running the program using Sudo or a normal user?

**Comment by mmarkus13** [comment]
Thanks for the fast response.

Am running with:
Windows 10 -> virtual box -> ubuntu16.04.1-desktop-amd64 - allocated 4gb ram 30gb fs.
system user is called mangos. 
clean install. The steps I did pre-install:
 As root: _sudo apt-get update
              sudo apt-get upgrade
              sudo apt-get install build-essential gcc g++ automake git-core_
then switched back to normal (mangos) user. _cd ~_
_git clone git://github.com/CollectiveIndustries/Mangos_Installer.git_
cd Mangos_Installer
since the installer is chmod 775 I just run it.
./mangos-ci-install.py

*********************************
Welcome: mangos
override root security locks-outs? [n] y
Preform Pre-Install + updates?: [n] y
We will now begin to process all dependencies required to build the MaNGOS server
Running Update as user: 
[sudo] password for mangos: 
root

....

Do you want to bypass compile? [n] 
Directory paths created for install and compile
Would you like to save source code? [n] y
Realm Name: [mangos-VirtualBox] Mordor
Hostname for ACCOUNT database (realmd): [localhost] 

Hostname for ACCOUNT database (realmd): [localhost] 
Hostname for MANGOS database (mangosd): [localhost] 
Port number for MySQL Server on MaNGOS_DB (localhost): [3306] 
Port number for MySQL Server on Realm_DB (localhost): [3306]
Name of the MaNGOS mysql user you wish to use: *******
Password for new user: *******
Before we can set-up the new MaNGOS user we need to log into mysql as root or another administrators account
MySQL ADMIN username: ******
ADMIN password: ********
Almost ready to start installing the Database's We need a few more things and then we're ready
New World Database name: [mangos-Mordor] 
New Character Database: [characters-Mordor] 
New ScriptDev2 Database: [scriptdev2-Mordor] 
which script library would you like to install [2]

[1] https://github.com/scriptdev2/scriptdev2-cata.git

[2] https://github.com/mangosthree/scripts.git

[3] https://github.com/CollectiveIndustries/scripts.git

ScriptDev2 [2]: 
New Account Database: [realmd-account] 
Which version of MaNGOS do you wish to use (1 vanilla - 5 MoP): [4] 
Log directory to use: [../logs] 
data directory for maps: [../data] 
Please enter the Realm ID below (if first realm installed use default)
RealmID: [1] 
Cloning into '/home/mangos/SOURCE/mangos3_ci_code/server'...
remote: Counting objects: 89315, done.
remote: Total 89315 (delta 0), reused 0 (delta 0), pack-reused 89315
Receiving objects: 100% (89315/89315), 53.98 MiB | 8.03 MiB/s, done.
Resolving deltas: 100% (74292/74292), done.
Checking connectivity... done.
Cloning into '/home/mangos/SOURCE/mangos3_ci_code/database'...
remote: Counting objects: 1831, done.
remote: Total 1831 (delta 0), reused 0 (delta 0), pack-reused 1831
Receiving objects: 100% (1831/1831), 39.18 MiB | 5.48 MiB/s, done.
Resolving deltas: 100% (497/497), done.
Checking connectivity... done.
Chaging Directory to: /home/mangos/SOURCE/mangos3_ci_code/server/src/bindings
INSTALLING: https://github.com/CollectiveIndustries/scripts.git
Cloning into './ScriptDev2'...
remote: Counting objects: 51964, done.
remote: Total 51964 (delta 0), reused 0 (delta 0), pack-reused 51964
Receiving objects: 100% (51964/51964), 48.96 MiB | 9.16 MiB/s, done.
Resolving deltas: 100% (42664/42664), done.
Checking connectivity... done.
Cloning into '/home/mangos/SOURCE/mangos3_ci_code/tools'...
remote: Counting objects: 231, done.
remote: Total 231 (delta 0), reused 0 (delta 0), pack-reused 231
Receiving objects: 100% (231/231), 1.70 MiB | 397.00 KiB/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "./mangos-ci-install.py", line 304, in <module>
    os.makedirs(os.path.join(SERV_CODE+"/server/", "objdir")) #main server bin directory
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/mangos/SOURCE/mangos3_ci_code/server/objdir'
mangos@mangos-VirtualBox:~/Mangos_Installer$

**Comment by Morketh** [comment]
That should be enough information to get me started fixing the bug. If i have any additional questions ill respond back here. Thank you again for finding this issue.

**Comment by mmarkus13** [comment]
is there something that I can help testing or try?

**Comment by mmarkus13** [comment]
Is there something that I could try or test to help?

**Comment by Morketh** [comment]
@mmarkus13 unfortunately no there's nothing to test. As you are probably aware I've been inactive for several years. This project is not forgotten but with only 2 developers on this, its been put on the back burner and ignored. Since this project was started there has been a lot of changes to the way WoW emulators work and I've moved over to TrinityCore.
